package com.restaurant.grandmasfood.exception.utils;

public interface ExceptionCode {
    String CLIENT_ALREADY_EXISTS_CODE = "EC01";
    String PRODUCT_ALREADY_EXISTS_CODE = "EP01";
    String CLIENT_INVALID_OR_MISSING_DATA_CODE = "EC12";
    String PRODUCT_INVALID_OR_MISSING_DATA_CODE = "EP12";
    String ORDER_INVALID_OR_MISSING_DATA_CODE = "EO11";
    String CLIENT_NOT_FOUND_CODE = "EC23";
    String PRODUCT_NOT_FOUND_CODE = "EP23";
    String ORDER_NOT_FOUND_CODE = "EO22";
    String CLIENT_INVALID_ATTRIBUTE_FORMAT_CODE = "EC34";
    String PRODUCT_INVALID_ATTRIBUTE_FORMAT_CODE = "EP34";
    String ORDER_INVALID_ATTRIBUTE_FORMAT_CODE = "EO33";
    String CLIENT_NO_CHANGES_IN_UPDATE_CODE = "EC45";
    String PRODUCT_NO_CHANGES_IN_UPDATE_CODE = "EP45";
    String FATAL_ERROR = "EFE00";
}
